steps:
  - id: 'tf init'
    name: 'hashicorp/terraform:1.7.0'
    args:
      - 'init'

  - id: 'tf plan'
    name: 'hashicorp/terraform:1.7.0'
    args:
      - 'plan'

  - id: 'tf apply'
    name: 'hashicorp/terraform:1.7.0'
    args:
      - 'apply'
      - '-auto-approve'

# Optional but recommended settings
options:
  logging: CLOUD_LOGGING_ONLY